In [35]:
#1
import numpy as np
x=np.random.randint(1,100,10)
print("orginal array:",x)
sorted=np.sort(x)
print("using sort:",sorted)
x.sort()
print(x)
#2
i=np.argsort(x)
print(i)
result=x[i]
print("x[i]:",result)
print("np.sort:",sorted)
print("Are they same:",np.array_equal(result,sorted))

orginal array: [18 74 97 74 68 74 23 31 49 22]
using sort: [18 22 23 31 49 68 74 74 74 97]
[18 22 23 31 49 68 74 74 74 97]
[0 1 2 3 4 5 6 7 8 9]
x[i]: [18 22 23 31 49 68 74 74 74 97]
np.sort: [18 22 23 31 49 68 74 74 74 97]
Are they same: True


In [45]:
#3
x=np.random.randint(1,100,(4,6))
print(x)
row_sorted=np.sort(x,axis=1)
cloumn_sorted=np.sort(x,axis=0)
print("row wise:",row_sorted)
print("col wise:",cloumn_sorted)



[[33 25 61 91 93 70]
 [98 49 92 64 22 17]
 [21 63 65 40 43 66]
 [82 89 11 73 88 93]]
row wise: [[25 33 61 70 91 93]
 [17 22 49 64 92 98]
 [21 40 43 63 65 66]
 [11 73 82 88 89 93]]
col wise: [[21 25 11 40 22 17]
 [33 49 61 64 43 66]
 [82 63 65 73 88 70]
 [98 89 92 91 93 93]]


In [63]:
x=np.random.randint(1,100,15)
print("orginal array: ",x)
result=np.partition(x,4)
print("partition method:",result)
print("smallest 4 integer:",result[:4])
res=np.sort(x)
print("using sort function:",res)
print("smallest 4 integer:",res[:4])

orginal array:  [25 27 19 13 91 93  8  4 66 19 37 26 59 67 59]
partition method: [13  8  4 19 19 25 93 27 66 91 37 26 59 67 59]
smallest 4 integer: [13  8  4 19]
using sort function: [ 4  8 13 19 19 25 26 27 37 59 59 66 67 91 93]
smallest 4 integer: [ 4  8 13 19]


In [67]:
#5
import numpy as np

student_names = np.array([
    "Rahul",
    "Priya",
    "Arjun",
    "Sneha",
    "Kiran"
])

scores = np.array([75, 92, 68, 85, 78])
i = np.argsort(scores)
ranked_names = student_names[i]
print("Scores:", scores)
print("Students ranked from lowest to highest:")

for name, score in zip(ranked_names, scores[i]):
    print(name, ":", score)

Scores: [75 92 68 85 78]
Students ranked from lowest to highest:
Arjun : 68
Rahul : 75
Kiran : 78
Sneha : 85
Priya : 92
